/* 成就定义：id 唯一，name/desc 走 steam 那种自嘲怪话，icon 从 icons/ 里挑的。
   雏形先接 8 个，以后加成就：往这个数组里插一条，再去触发点调用
   Achievements.unlock / bump / visit 就行，不用碰引擎代码。 */
window.ACHIEVEMENTS = [
  { id:'shrine-denied', name:'被神社拒入',
    desc:'抽完今日签之后，还不死心地翻回签筒页 5 次。神明已经下班了。',
    icon:'icons/px/Locked.png' },
  { id:'tarot-addict', name:'还没算出喜欢的结果吗？',
    desc:'同一个牌阵连续点「再寻求一次」5 次。命运不是老虎机。',
    icon:'icons/px/moon.png' },
  { id:'book-worn-out', name:'图书馆常客',
    desc:'累计翻阅答案之书 20 次。',
    icon:'icons/px/Book.png' },
  { id:'vending-broke', name:'贩售机至尊黑卡客户',
    desc:'往贩售机投币 10 次。',
    icon:'icons/px/Coin.png' },
  { id:'archive-digger', name:'不可回收',
    desc:'请勿拾取认知污染有害垃圾。',
    icon:'icons/px/Trashbin.png' },
  { id:'hotline-completionist', name:'我得听听怎么回事',
    desc:'点开过全部 4 通来电归档。都听完了，你自己还好吗？',
    icon:'icons/px/Telephone.png' },
  { id:'dj-timetoki', name:'DJ TIMETOKI',
    desc:'手动切歌 10 次。别切了，好好听完一首完整的。',
    icon:'icons/px/CD.png' },
  { id:'block-breaker', name:'方块人格',
    desc:'点开过 Minecraft。逃避现实，但好歹换了个像素风的现实。',
    icon:'icons/largeicons/MC.png' },
  { id:'hotline-regular', name:'骚扰电话',
    desc:'我们已经记住你的号码了。',
    icon:'icons/px/Telephone.png' },
  { id:'wall-clicker', name:'手账贴纸爱好者',
    desc:'它们会一直长回来。',
    icon:'icons/largeicons/Contact.png' },
  { id:'qq-ghost', name:'已读不回',
    desc:'只是想看看有没有人在吗？',
    icon:'icons/largeicons/MSN.png' },
  { id:'read-the-fine-print', name:'规则怪谈？',
    desc:'现在你可以入职了。',
    icon:'icons/largeicons/Blog.png' },
  { id:'silent-treatment', name:'不许吵',
    desc:'有些东西还是安静点比较好。',
    icon:'icons/largeicons/Winamp.png' },
  { id:'full-listen', name:'能给我一份歌单吗？',
    desc:'别切了，你已经做到了。',
    icon:'icons/px/CD.png' },
  { id:'vending-flood', name:'投币过载',
    desc:'它已经不堪重负了。',
    icon:'icons/px/Coin.png' },
  { id:'replay-the-same-call', name:'不要制止重复的痛苦',
    desc:'守则第 02 条：重复内容无需制止。',
    icon:'icons/px/Telephone.png' },
  { id:'false-start', name:'开始了，但没有',
    desc:'它什么都不会发生。',
    icon:'icons/largeicons/1.png' },
  { id:'completionist', name:'+86自杀援助中心资深客户',
    desc:'祝贺，也节哀。',
    icon:'icons/px/Trophy.png' }
];
