/* 塔罗 · 牌面文件名 → 中文名 + 简析
   文件在 picture/cards/ ，文件名与截图一致（含 Trhee 这种拼写）。抽牌时排除 card-back。 */
window.TAROT = [
/* —— 大阿卡纳 —— */
{f:"The fool.png",         n:"愚者",     r:"新的开始 · 冒险 · 纯真"},
{f:"The Magician.png",     n:"魔术师",   r:"创造 · 行动力 · 掌控"},
{f:"The High Priestess.png",n:"女祭司",  r:"直觉 · 潜意识 · 秘密"},
{f:"Empress.png",          n:"女皇",     r:"丰饶 · 母性 · 滋养"},
{f:"The Emperor.png",      n:"皇帝",     r:"权威 · 秩序 · 稳定"},
{f:"The Hierophant.png",   n:"教皇",     r:"传统 · 指引 · 信念"},
{f:"Lovers.png",           n:"恋人",     r:"关系 · 选择 · 结合"},
{f:"The Chariot.png",      n:"战车",     r:"意志 · 前进 · 掌控方向"},
{f:"The strength.png",     n:"力量",     r:"勇气 · 内在力量 · 温柔的坚定"},
{f:"The hermit.png",       n:"隐士",     r:"独处 · 内省 · 寻找答案"},
{f:"The wheel of fortune.png",n:"命运之轮",r:"转机 · 循环 · 变化"},
{f:"The justice.png",      n:"正义",     r:"公正 · 因果 · 权衡"},
{f:"The hanged man.png",   n:"倒吊人",   r:"停顿 · 换个角度 · 放下"},
{f:"The death.png",        n:"死神",     r:"结束 · 转变 · 重生"},
{f:"The Temperance.png",   n:"节制",     r:"平衡 · 调和 · 耐心"},
{f:"The Devil.png",        n:"恶魔",     r:"欲望 · 束缚 · 执念"},
{f:"Tower.png",            n:"高塔",     r:"突变 · 崩解 · 觉醒"},
{f:"The stars.png",        n:"星星",     r:"希望 · 疗愈 · 指引"},
{f:"The moon.png",         n:"月亮",     r:"幻象 · 不安 · 潜意识"},
{f:"The sun.png",          n:"太阳",     r:"喜悦 · 成功 · 光明"},
{f:"The judgement.png",    n:"审判",     r:"觉醒 · 召唤 · 重新评估"},
{f:"The world.png",        n:"世界",     r:"圆满 · 完成 · 整合"},

/* —— 圣杯 Cups（情感）—— */
{f:"Ace of cups.png",  n:"圣杯 ·首牌", r:"情感萌发 · 爱 · 新感受"},
{f:"Two of cups.png",  n:"圣杯 ·二",   r:"结合 · 互相吸引 · 关系"},
{f:"Trhee of cups.png",n:"圣杯 ·三",   r:"欢聚 · 友情 · 庆祝"},
{f:"Four of cups.png", n:"圣杯 ·四",   r:"倦怠 · 错过 · 重新审视"},
{f:"Five of cups.png", n:"圣杯 ·五",   r:"失落 · 遗憾 · 仍有余留"},
{f:"Six of cups.png",  n:"圣杯 ·六",   r:"回忆 · 童真 · 旧情"},
{f:"Seven of cups.png",n:"圣杯 ·七",   r:"幻想 · 选择太多 · 迷惑"},
{f:"Eight of cups.png",n:"圣杯 ·八",   r:"离开 · 追寻更深 · 放手"},
{f:"Nine of cups.png", n:"圣杯 ·九",   r:"满足 · 心愿达成"},
{f:"Ten of cups.png",  n:"圣杯 ·十",   r:"圆满 · 家庭 · 幸福"},
{f:"Page of cups.png", n:"圣杯 ·侍者", r:"敏感 · 灵感 · 温柔讯息"},
{f:"Knight of cups.png",n:"圣杯 ·骑士",r:"浪漫 · 追随内心 · 邀约"},
{f:"Queen of cups.png",n:"圣杯 ·王后", r:"共情 · 包容 · 情感成熟"},
{f:"King of cups.png", n:"圣杯 ·国王", r:"情绪掌控 · 沉稳 · 关怀"},

/* —— 星币 Gold/Pentacles（现实）—— */
{f:"Ace of gold.png",  n:"星币 ·首牌", r:"机会 · 物质起点 · 落地"},
{f:"Two of gold.png",  n:"星币 ·二",   r:"权衡 · 灵活 · 多头兼顾"},
{f:"Trhee of gold.png",n:"星币 ·三",   r:"合作 · 技艺 · 打好基础"},
{f:"Four of gold.png", n:"星币 ·四",   r:"守成 · 掌控 · 不愿放手"},
{f:"Five of gold.png", n:"星币 ·五",   r:"匮乏 · 困顿 · 别忽略援手"},
{f:"Six of gold.png",  n:"星币 ·六",   r:"给予 · 分享 · 收支平衡"},
{f:"Seven of gold.png",n:"星币 ·七",   r:"等待 · 耕耘 · 评估成果"},
{f:"Eight of gold.png",n:"星币 ·八",   r:"专注 · 打磨 · 精进"},
{f:"Nine of gold.png", n:"星币 ·九",   r:"自足 · 独立 · 享受成果"},
{f:"Ten of gold.png",  n:"星币 ·十",   r:"稳固 · 传承 · 长久富足"},
{f:"Page of gold.png", n:"星币 ·侍者", r:"学习 · 务实 · 新机会"},
{f:"Knight of gold.png",n:"星币 ·骑士",r:"踏实 · 坚持 · 稳步推进"},
{f:"Queen of gold.png",n:"星币 ·王后", r:"务实 · 照料 · 丰盛"},
{f:"King of gold.png", n:"星币 ·国王", r:"富足 · 稳健 · 掌管资源"},

/* —— 宝剑 Swords（思维）—— */
{f:"Ace of swords.png",  n:"宝剑 ·首牌", r:"清晰 · 突破 · 真相"},
{f:"Two of swords.png",  n:"宝剑 ·二",   r:"僵持 · 逃避抉择 · 需面对"},
{f:"Trhee of swords.png",n:"宝剑 ·三",   r:"心碎 · 伤痛 · 释放"},
{f:"Four of swords.png", n:"宝剑 ·四",   r:"休息 · 沉淀 · 恢复"},
{f:"Five of swords.png", n:"宝剑 ·五",   r:"冲突 · 争胜 · 得不偿失"},
{f:"Six of swords.png",  n:"宝剑 ·六",   r:"过渡 · 离开 · 走向平静"},
{f:"Seven of swords.png",n:"宝剑 ·七",   r:"策略 · 隐瞒 · 独自行动"},
{f:"Eight of swords.png",n:"宝剑 ·八",   r:"受限 · 自我设限 · 可解开"},
{f:"Nine of swords.png", n:"宝剑 ·九",   r:"焦虑 · 忧思 · 夜不能寐"},
{f:"Ten of swords.png",  n:"宝剑 ·十",   r:"谷底 · 结束 · 黎明将至"},
{f:"Page of swords.png", n:"宝剑 ·侍者", r:"好奇 · 机敏 · 打探消息"},
{f:"Knight of swords.png",n:"宝剑 ·骑士",r:"果断 · 冲劲 · 直接行动"},
{f:"Queen of swords.png",n:"宝剑 ·王后", r:"理性 · 独立 · 看清事实"},
{f:"King of swords.png", n:"宝剑 ·国王", r:"理智 · 判断 · 原则"},

/* —— 权杖 Wands（行动）—— */
{f:"Ace of wands.png",  n:"权杖 ·首牌", r:"灵感 · 冲劲 · 新点子"},
{f:"Two of wands.png",  n:"权杖 ·二",   r:"规划 · 展望 · 做选择"},
{f:"Trhee of wands.png",n:"权杖 ·三",   r:"扩展 · 等待回报 · 远方"},
{f:"Four of wands.png", n:"权杖 ·四",   r:"庆祝 · 稳定 · 团聚"},
{f:"Five of wands.png", n:"权杖 ·五",   r:"竞争 · 摩擦 · 各执一词"},
{f:"Six of wands.png",  n:"权杖 ·六",   r:"胜利 · 认可 · 好消息"},
{f:"Seven of wands.png",n:"权杖 ·七",   r:"坚守 · 应战 · 捍卫立场"},
{f:"Eight of wands.png",n:"权杖 ·八",   r:"迅速 · 进展 · 消息将至"},
{f:"Nine of wands.png", n:"权杖 ·九",   r:"坚持 · 疲惫但不放弃"},
{f:"Ten of wands.png",  n:"权杖 ·十",   r:"重担 · 责任过多 · 需放下"},
{f:"Page of wands.png", n:"权杖 ·侍者", r:"热情 · 探索 · 跃跃欲试"},
{f:"Knight of wands.png",n:"权杖 ·骑士",r:"行动 · 冒险 · 冲动"},
{f:"Queen of wands.png",n:"权杖 ·王后", r:"自信 · 魅力 · 热情"},
{f:"King of wands.png", n:"权杖 ·国王", r:"领导 · 远见 · 魄力"}
];
